/**
 * Comprehensive permissions for POS system
 * Organized by category for easier management
 */

export const PERMISSIONS = {
  // Sales Operations
  CREATE_SALE: "CREATE_SALE",
  VOID_SALE: "VOID_SALE",
  VIEW_SALES: "VIEW_SALES",
  APPLY_DISCOUNT: "APPLY_DISCOUNT",

  // Returns
  CREATE_RETURN: "CREATE_RETURN",
  VIEW_RETURNS: "VIEW_RETURNS",

  // Reports
  VIEW_PROFIT_REPORT: "VIEW_PROFIT_REPORT",
  VIEW_SALES_REPORT: "VIEW_SALES_REPORT",
  EXPORT_REPORTS: "EXPORT_REPORTS",

  // User Management
  CREATE_USER: "CREATE_USER",
  VIEW_USERS: "VIEW_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_OWN_PROFILE: "UPDATE_OWN_PROFILE",

  // Role Management
  MANAGE_ROLES: "MANAGE_ROLES",
  ASSIGN_ROLES: "ASSIGN_ROLES",

  // Permission Management
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  ASSIGN_PERMISSIONS: "ASSIGN_PERMISSIONS",

  // Category Management
  CREATE_CATEGORY: "CREATE_CATEGORY",
  VIEW_CATEGORIES: "VIEW_CATEGORIES",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  // Product Management
  CREATE_PRODUCT: "CREATE_PRODUCT",
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  BULK_IMPORT_PRODUCTS: "BULK_IMPORT_PRODUCTS",

  // Inventory
  MANAGE_INVENTORY: "MANAGE_INVENTORY",
  VIEW_INVENTORY: "VIEW_INVENTORY",

  // Repair Management
  CREATE_REPAIR: "CREATE_REPAIR",
  VIEW_REPAIRS: "VIEW_REPAIRS",
  VIEW_OWN_REPAIRS: "VIEW_OWN_REPAIRS",
  ASSIGN_REPAIR: "ASSIGN_REPAIR",
  UPDATE_REPAIR: "UPDATE_REPAIR",
  COMPLETE_REPAIR: "COMPLETE_REPAIR",
  COLLECT_REPAIR_PAYMENT: "COLLECT_REPAIR_PAYMENT",
  CANCEL_REPAIR: "CANCEL_REPAIR",

  // Warranty Management
  CREATE_WARRANTY: "CREATE_WARRANTY",
  VIEW_WARRANTIES: "VIEW_WARRANTIES",
  UPDATE_WARRANTY: "UPDATE_WARRANTY",
  VOID_WARRANTY: "VOID_WARRANTY",
  CREATE_WARRANTY_CLAIM: "CREATE_WARRANTY_CLAIM",
  VIEW_WARRANTY_REPORTS: "VIEW_WARRANTY_REPORTS",

  // Settings
  MANAGE_SETTINGS: "MANAGE_SETTINGS",

  // Promotions
  MANAGE_PROMOTIONS: "MANAGE_PROMOTIONS",
  VIEW_PROMOTIONS: "VIEW_PROMOTIONS"
};

// Permission categories for grouping in UI
export const PERMISSION_CATEGORIES = {
  SALES: ["CREATE_SALE", "VOID_SALE", "VIEW_SALES", "APPLY_DISCOUNT"],
  RETURNS: ["CREATE_RETURN", "VIEW_RETURNS"],
  PROMOTIONS: ["MANAGE_PROMOTIONS", "VIEW_PROMOTIONS"],
  REPORTS: ["VIEW_PROFIT_REPORT", "VIEW_SALES_REPORT", "EXPORT_REPORTS"],
  USERS: ["CREATE_USER", "VIEW_USERS", "UPDATE_USER", "DELETE_USER", "UPDATE_OWN_PROFILE"],
  ROLES: ["MANAGE_ROLES", "ASSIGN_ROLES"],
  PERMISSIONS: ["MANAGE_PERMISSIONS", "ASSIGN_PERMISSIONS"],
  CATEGORIES: ["CREATE_CATEGORY", "VIEW_CATEGORIES", "UPDATE_CATEGORY", "DELETE_CATEGORY"],
  PRODUCTS: ["CREATE_PRODUCT", "VIEW_PRODUCTS", "UPDATE_PRODUCT", "DELETE_PRODUCT", "BULK_IMPORT_PRODUCTS"],
  INVENTORY: ["MANAGE_INVENTORY", "VIEW_INVENTORY"],
  REPAIRS: [
    "CREATE_REPAIR", "VIEW_REPAIRS", "VIEW_OWN_REPAIRS",
    "ASSIGN_REPAIR", "UPDATE_REPAIR", "COMPLETE_REPAIR",
    "COLLECT_REPAIR_PAYMENT", "CANCEL_REPAIR"
  ],
  WARRANTIES: [
    "CREATE_WARRANTY", "VIEW_WARRANTIES", "UPDATE_WARRANTY",
    "VOID_WARRANTY", "CREATE_WARRANTY_CLAIM", "VIEW_WARRANTY_REPORTS"
  ],
  SETTINGS: ["MANAGE_SETTINGS"]
};
